const rootContainer = pixiApplication.stage;
{;
   const cobalt_0 = new PIXI.Container();
   {;
      const texture0 = PIXI.Texture.fromImage('assets/bunny.png');
      const cobaltBunny1_0 = new PIXI.Sprite(texture0);
      cobaltBunny1_0['name'] = 'cobaltBunny1';
      cobaltBunny1_0['x'] = 0;
      cobaltBunny1_0['y'] = 0;
      cobalt_0.addChild(cobaltBunny1_0);
   };
   {;
      const texture0 = PIXI.Texture.fromImage('assets/bunny.png');
      const cobaltBunny2_0 = new PIXI.Sprite(texture0);
      cobaltBunny2_0['name'] = 'cobaltBunny2';
      cobaltBunny2_0['x'] = 10;
      cobaltBunny2_0['y'] = 10;
      cobalt_0.addChild(cobaltBunny2_0);
   };
   {;
      const subcontainer_0 = new PIXI.Container();
      {;
         const texture0 = PIXI.Texture.fromImage('assets/bunny.png');
         const bunny1_0 = new PIXI.Sprite(texture0);
         bunny1_0['name'] = 'bunny1';
         bunny1_0['x'] = 20;
         bunny1_0['y'] = 20;
         subcontainer_0.addChild(bunny1_0);
      };
      subcontainer_0['name'] = 'subcontainer';
      cobalt_0.addChild(subcontainer_0);
   };
   cobalt_0['name'] = 'cobalt';
   cobalt_0['x'] = 50;
   cobalt_0['y'] = 10;
   rootContainer.addChild(cobalt_0);
};
{;
   const texture0 = PIXI.Texture.fromImage('assets/bunny.png');
   const freeBunny_0 = new PIXI.Sprite(texture0);
   freeBunny_0['name'] = 'freeBunny';
   freeBunny_0['x'] = 50;
   freeBunny_0['y'] = 100;
   rootContainer.addChild(freeBunny_0);
};
{;
   /* RedCircle */;
   const RedCircle_0 = new PIXI.Graphics();
   RedCircle_0.lineStyle(0);
   RedCircle_0.beginFill(0xFF0000, 1);
   RedCircle_0.drawCircle(50,50,30);
   RedCircle_0.endFill();
   RedCircle_0['x'] = 50;
   RedCircle_0['y'] = 50;
   RedCircle_0['radius'] = 30;
   RedCircle_0['alpha'] = 0.7;
   rootContainer.addChild(RedCircle_0);
};
